# Generated by Django 5.2.3 on 2025-08-22 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0002_remove_station_x_remove_station_y_position_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisement', to='reklamaproject.position'),
        ),
    ]
