# Generated by Django 5.2.3 on 2025-08-22 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0003_alter_advertisement_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='reklamaproject.station'),
        ),
        migrations.AlterField(
            model_name='station',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='reklamaproject.metroline'),
        ),
    ]
