# Generated by Django 5.2.3 on 2025-08-25 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0004_alter_position_station_alter_station_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='x',
        ),
        migrations.RemoveField(
            model_name='position',
            name='y',
        ),
    ]
