# Generated by Django 5.2.3 on 2025-08-26 05:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0005_remove_position_x_remove_position_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='schema_image',
        ),
        migrations.AddField(
            model_name='station',
            name='schema_file',
            field=models.FileField(blank=True, help_text='Bekat sxemasi (rasm yoki PDF)', null=True, upload_to='station_schemas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
    ]
