# Generated by Django 5.2.3 on 2025-08-26 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0006_remove_station_schema_image_station_schema_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='schema_file',
            new_name='schema_image',
        ),
    ]
