# Generated by Django 5.2.3 on 2025-08-26 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0007_rename_schema_file_station_schema_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='reklamaproject.position'),
        ),
        migrations.AlterField(
            model_name='advertisementarchive',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reklamaproject.position'),
        ),
        migrations.AlterField(
            model_name='advertisementarchive',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reklamaproject.station'),
        ),
    ]
