# Generated by Django 5.2.3 on 2025-08-28 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0008_alter_advertisement_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementarchive',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reklamaproject.position'),
        ),
        migrations.AlterField(
            model_name='advertisementarchive',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reklamaproject.station'),
        ),
    ]
